import pandas as pd

print(pd.read_csv(r'C:\Users\German\Desktop\us-500.csv'))
first_10_rows=pd.read_csv(r'C:\Users\German\Desktop\us-500.csv').head(10)
print(first_10_rows)
first_5_rows=pd.read_csv(r'C:\Users\German\Desktop\us-500.csv').head()
print(first_5_rows)
print(type(first_10_rows))
print(first_10_rows.to_csv('my_csv', index=False))
df = pd.read_excel(r'C:\Users\German\Desktop\SampleData.xlsx', sheet_name='SalesOrders')
print(df)
print(df.to_excel('MyExcel.xlsx', sheet_name='MySheet'))
html_data = pd.read_html('https://en.wikipedia.org/wiki/List_of_largest_cities_on_the_United_States_West_Coast')
print(type(html_data))
print(html_data[0])
print(html_data[1])
data = html_data[1].head(20)
print(data.to_csv('html_data.csv'))
json_data = data.to_json()
print(json_data)
